DO } BEGIN
  CREATE TYPE "PhotoPlan" AS ENUM ('FREE_3','PHOTO_PLUS_25');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END };

DO } BEGIN
  CREATE TYPE "BillingStatus" AS ENUM ('FREE','ACTIVE','PAST_DUE','CANCELED');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END };

ALTER TABLE "Listing"
  ADD COLUMN IF NOT EXISTS "photoPlan" "PhotoPlan" NOT NULL DEFAULT 'FREE_3',
  ADD COLUMN IF NOT EXISTS "featuredHome" BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS "billingStatus" "BillingStatus" NOT NULL DEFAULT 'FREE',
  ADD COLUMN IF NOT EXISTS "billingProvider" TEXT,
  ADD COLUMN IF NOT EXISTS "braintreeSubscriptionId" TEXT,
  ADD COLUMN IF NOT EXISTS "billingAddons" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN IF NOT EXISTS "billingCurrency" TEXT NOT NULL DEFAULT 'USD',
  ADD COLUMN IF NOT EXISTS "billingMonthlyCents" INTEGER,
  ADD COLUMN IF NOT EXISTS "billingCurrentPeriodStart" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "billingCurrentPeriodEnd" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "cancelAtPeriodEnd" BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS "canceledAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "lastPaidAt" TIMESTAMP(3);
